name: bot_taphoa
description: Bot quan ly tap hoa
environment:
  sdk: ^3.0.0

dependencies:
  teledart: ^0.6.1 # Thư viện Telegram
  supabase: ^2.0.0 # Thư viện kết nối Supabase (bản Dart, không phải Flutter)
  intl: ^0.19.0
